// Public surface of the generated REST client (D-09-1). Import models + the
// client factory from here; the generated `schema.ts` is regenerated by
// `scripts/gen-api.sh` (committed, not runtime-generated).
import type { components } from "./schema";

export type { ApiErrorBody, RateLimit, TokenGetter } from "./client";
export { ApiError, createApiClient, readRateLimit, unwrap } from "./client";
export type { components, paths } from "./schema";

type Schemas = components["schemas"];

// Responses
export type PersonaSummary = Schemas["PersonaSummary"];
export type PersonaDetail = Schemas["PersonaDetail"];
export type ConversationSummary = Schemas["ConversationSummary"];
export type ConversationDetail = Schemas["ConversationDetail"];
export type MessageView = Schemas["MessageView"];
export type RunStatusResponse = Schemas["RunStatusResponse"];
export type ToolSummary = Schemas["ToolSummary"];
export type CreditsResponse = Schemas["CreditsResponse"];
export type UsageEntry = Schemas["UsageEntry"];

// Requests
export type CreatePersonaRequest = Schemas["CreatePersonaRequest"];
export type UpdatePersonaRequest = Schemas["UpdatePersonaRequest"];
export type AuthorPersonaRequest = Schemas["AuthorPersonaRequest"];
export type CreateConversationRequest = Schemas["CreateConversationRequest"];
export type PostMessageRequest = Schemas["PostMessageRequest"];
export type ChannelContext = Schemas["ChannelContext"];
export type StartRunRequest = Schemas["StartRunRequest"];
export type RespondToRunRequest = Schemas["RespondToRunRequest"];
