/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/personas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Personas
     * @description List the caller's personas (paginated; RLS-scoped).
     */
    get: operations["list_personas_v1_personas_get"];
    put?: never;
    /**
     * Create Persona
     * @description Create a persona from YAML; populate its memory stores (D-08-8).
     */
    post: operations["create_persona_v1_personas_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/author": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Author Persona
     * @description Generate a draft persona from a description, then create it (§6.3).
     */
    post: operations["author_persona_v1_personas_author_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Persona
     * @description Get a persona's YAML + metadata (404 if not the caller's).
     */
    get: operations["get_persona_v1_personas__persona_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Persona
     * @description Delete a persona + all its conversations and memory (cascade).
     */
    delete: operations["delete_persona_v1_personas__persona_id__delete"];
    options?: never;
    head?: never;
    /**
     * Update Persona
     * @description Replace a persona's YAML (re-validated) and re-index its memory.
     */
    patch: operations["update_persona_v1_personas__persona_id__patch"];
    trace?: never;
  };
  "/v1/personas/{persona_id}/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Conversation
     * @description Start a new conversation against a persona.
     */
    post: operations["create_conversation_v1_personas__persona_id__conversations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Conversations
     * @description List the caller's conversations (paginated; RLS-scoped).
     */
    get: operations["list_conversations_v1_conversations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/conversations/{conversation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Conversation
     * @description Get a conversation's full message history (404 if not the caller's).
     */
    get: operations["get_conversation_v1_conversations__conversation_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Conversation
     * @description Delete a conversation + all its messages (cascade; 404 if not the caller's).
     */
    delete: operations["delete_conversation_v1_conversations__conversation_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/conversations/{conversation_id}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Post Message
     * @description Send a message; stream the response as SSE (§5.2, KEYSTONE 1).
     */
    post: operations["post_message_v1_conversations__conversation_id__messages_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Run
     * @description Start an agentic run (returns the run_id immediately; runs in background).
     */
    post: operations["start_run_v1_personas__persona_id__runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Run
     * @description Get a run's status + accumulated steps (RLS-scoped → 404).
     */
    get: operations["get_run_v1_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/runs/{run_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream Events
     * @description Stream the run's events as SSE (live, from the in-process event bus).
     */
    get: operations["stream_events_v1_runs__run_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/runs/{run_id}/respond": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Respond
     * @description Deliver an answer to a run awaiting an ask-user question.
     */
    post: operations["respond_v1_runs__run_id__respond_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/runs/{run_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel
     * @description Cancel a running run (stops at the next step boundary → cancelled).
     */
    post: operations["cancel_v1_runs__run_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/credits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Credits
     * @description The caller's current credit balance (stub counter; §5.5).
     */
    get: operations["get_credits_v1_me_credits_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Usage
     * @description The caller's per-turn token usage (§5.5; turn_logs, RLS-scoped).
     */
    get: operations["get_usage_v1_me_usage_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Liveness + DB connectivity check.
     */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tools
     * @description List the available tools (name + description).
     */
    get: operations["list_tools_v1_tools_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/skills": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Skills
     * @description List the available skills (name + description).
     */
    get: operations["list_skills_v1_skills_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AuthorPersonaRequest
     * @description LLM-assisted authoring from a natural-language description (§5.1, §6.3).
     */
    AuthorPersonaRequest: {
      /** Description */
      description: string;
    };
    /**
     * ChannelContext
     * @description Opaque connector context passed through the chat endpoint (D-08-3).
     *
     *     The API stores this on the message row and never interprets it — ``platform``
     *     is a free-form string, NEVER an enum the API branches on. All connector logic
     *     lives in the future spec-12 connectors. Null/absent is the web-UI case.
     */
    ChannelContext: {
      /** Platform */
      platform: string;
      /** Platform User Id */
      platform_user_id?: string | null;
      /** Platform Chat Id */
      platform_chat_id?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: string;
      };
    };
    /**
     * ConversationDetail
     * @description Full conversation history.
     */
    ConversationDetail: {
      /** Id */
      id: string;
      /** Persona Id */
      persona_id: string;
      /** Title */
      title: string;
      /** Messages */
      messages: components["schemas"]["MessageView"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ConversationSummary
     * @description A conversation in a list view.
     */
    ConversationSummary: {
      /** Id */
      id: string;
      /** Persona Id */
      persona_id: string;
      /** Title */
      title: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * CreateConversationRequest
     * @description Start a new conversation against a persona.
     */
    CreateConversationRequest: {
      /**
       * Title
       * @default
       */
      title: string;
    };
    /**
     * CreatePersonaRequest
     * @description Create a persona from a YAML document (validated against the v1.0 schema).
     *
     *     ``avatar_url`` is an optional presentation field (not part of the YAML
     *     schema) — the persona-list / chat-header visual identity.
     */
    CreatePersonaRequest: {
      /** Yaml */
      yaml: string;
      /** Avatar Url */
      avatar_url?: string | null;
    };
    /**
     * CreditsResponse
     * @description The user's current credit balance (stub counter).
     */
    CreditsResponse: {
      /** Balance */
      balance: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * MessageView
     * @description A single message in a conversation history.
     */
    MessageView: {
      /** Id */
      id: string;
      /** Role */
      role: string;
      /** Content */
      content: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Channel */
      channel?: {
        [key: string]: unknown;
      } | null;
    };
    /**
     * PersonaDetail
     * @description A persona's full detail (YAML + metadata).
     */
    PersonaDetail: {
      /** Id */
      id: string;
      /** Yaml */
      yaml: string;
      /** Schema Version */
      schema_version: string;
      /** Avatar Url */
      avatar_url?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * PersonaSummary
     * @description A persona in a list view (no full YAML).
     */
    PersonaSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Role */
      role: string;
      /** Avatar Url */
      avatar_url?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * PostMessageRequest
     * @description Send a user message; the response streams over SSE (§5.2).
     *
     *     ``channel`` is the optional connector passthrough (D-08-3) — null for the
     *     web UI. The runtime ignores it in v0.1; the API just stores it on the
     *     message row and echoes ``format_hints`` on the ``done`` event.
     */
    PostMessageRequest: {
      /** Content */
      content: string;
      channel?: components["schemas"]["ChannelContext"] | null;
    };
    /**
     * RespondToRunRequest
     * @description Answer an ask-user question raised by a running agentic loop (§5.3).
     */
    RespondToRunRequest: {
      /** Answer */
      answer: string;
    };
    /**
     * RunStatusResponse
     * @description A run's status + its accumulated steps (JSON-serialised Run/Step).
     */
    RunStatusResponse: {
      /** Id */
      id: string;
      /** Persona Id */
      persona_id: string;
      /** Task */
      task: string;
      /** Status */
      status: string;
      /** Steps */
      steps?: {
        [key: string]: unknown;
      }[];
      /** Output */
      output?: string | null;
      /** Error */
      error?: string | null;
    };
    /**
     * StartRunRequest
     * @description Start an agentic run for a task (§5.3).
     */
    StartRunRequest: {
      /** Task */
      task: string;
    };
    /**
     * ToolSummary
     * @description A tool or skill name + description (read-only listing).
     */
    ToolSummary: {
      /** Name */
      name: string;
      /** Description */
      description: string;
    };
    /**
     * UpdatePersonaRequest
     * @description Replace a persona's YAML (re-validated against the v1.0 schema).
     */
    UpdatePersonaRequest: {
      /** Yaml */
      yaml: string;
      /** Avatar Url */
      avatar_url?: string | null;
    };
    /**
     * UsageEntry
     * @description One usage-log row (per-turn telemetry, paginated).
     */
    UsageEntry: {
      /** Persona Id */
      persona_id?: string | null;
      /** Tier Used */
      tier_used: string;
      /** Model Name */
      model_name: string;
      /** Prompt Tokens */
      prompt_tokens: number;
      /** Completion Tokens */
      completion_tokens: number;
      /** Cost Cents */
      cost_cents: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_personas_v1_personas_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_persona_v1_personas_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePersonaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  author_persona_v1_personas_author_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthorPersonaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_persona_v1_personas__persona_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_persona_v1_personas__persona_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_persona_v1_personas__persona_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePersonaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_conversation_v1_personas__persona_id__conversations_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateConversationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_conversations_v1_conversations_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_conversation_v1_conversations__conversation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_conversation_v1_conversations__conversation_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_message_v1_conversations__conversation_id__messages_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PostMessageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_run_v1_personas__persona_id__runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_v1_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stream_events_v1_runs__run_id__events_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  respond_v1_runs__run_id__respond_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RespondToRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_v1_runs__run_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_credits_v1_me_credits_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreditsResponse"];
        };
      };
    };
  };
  get_usage_v1_me_usage_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsageEntry"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  list_tools_v1_tools_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ToolSummary"][];
        };
      };
    };
  };
  list_skills_v1_skills_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ToolSummary"][];
        };
      };
    };
  };
}
