/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/v1/personas": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Personas
     * @description List the caller's personas (paginated; RLS-scoped).
     */
    get: operations["list_personas_v1_personas_get"];
    put?: never;
    /**
     * Create Persona
     * @description Create a persona from YAML; populate memory stores; return immediately.
     *
     *     The row + memory chunks are written synchronously (so the persona exists the
     *     moment this returns), then the response is sent with ``avatar_url=null`` (F1's
     *     default renders) and any auto-voice unset (the global default voices it). The
     *     voice auto-pick and the avatar auto-generation — which together added ~30s to
     *     the critical path — run in a ``BackgroundTasks`` job AFTER the response
     *     (:func:`_enrich_persona_after_create`), which re-establishes the owner's RLS
     *     scope before its writes (cloud) and fills in voice + avatar. The web detail
     *     surface bounded-polls ``GET /v1/personas/{id}`` until they appear.
     *
     *     Auto-generation only runs when the builder supplied no avatar (D-29-3); a
     *     user-supplied ``avatar_url`` always wins (criterion 6) and short-circuits the
     *     background avatar hook. Everything stays fail-soft (D-29-X-fail-soft).
     */
    post: operations["create_persona_v1_personas_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/author": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Author Persona
     * @description Generate a DRAFT persona from a description for review (D-10-2).
     *
     *     Returns the draft envelope (YAML + clarifying questions + prompt version) —
     *     it does NOT create a persona row. The user reviews/refines, then saves via
     *     ``POST /v1/personas``. The flat authoring credit is deducted per call (the
     *     cost is the frontier-model call, not a row; D-10-8).
     */
    post: operations["author_persona_v1_personas_author_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/author/refine": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refine Persona
     * @description Refine a draft persona by answering a clarifying question (§4, D-10-2).
     *
     *     Stateless: the request carries ``round`` (refinements already applied); the
     *     server rejects ``round >= 3`` as the backstop on the 3-round cap (D-10-5).
     *     Returns the updated draft envelope; deducts the flat authoring credit.
     */
    post: operations["refine_persona_v1_personas_author_refine_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/recommend-tools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Recommend Tools
     * @description Recommend a ranked tool subset for a persona description (spec 26 T09).
     *
     *     Authoring-time assist: given the natural-language description, a single
     *     mid-tier call (D-26-2) returns up to 10 catalog-valid tool recommendations,
     *     highest-confidence first. Reuses the description-only ``AuthorPersonaRequest``
     *     body. Deducts the flat authoring credit (a mid-tier LLM call).
     */
    post: operations["recommend_tools_v1_personas_recommend_tools_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/recommend-capabilities": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Recommend Capabilities
     * @description Recommend a unified, provider-tagged capability set (spec 27 T10).
     *
     *     The D-26-10 generalisation of ``/recommend-tools``: one mid-tier call ranks
     *     built-in tools, skills, and MCP servers together (each tagged with its
     *     provider), capped at the combined maximum (D-27-13). Deducts the same flat
     *     authoring credit (a mid-tier LLM call).
     */
    post: operations["recommend_capabilities_v1_personas_recommend_capabilities_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}/tools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Grant Tool
     * @description Enable a tool on the persona's allow-list via runtime consent (spec 26 T11).
     *
     *     Called when the user accepts a runtime tool-gap offer (T10). Adds the tool to
     *     the persona's ``tools`` list (persisted in the YAML column — no migration)
     *     and records the grant as a versioned ``persona_self`` self-fact (force +
     *     confidence ≥ 0.8 + reason, D-26-X-self-facts-consent-write-contract). Returns
     *     the updated persona detail. Idempotent: re-granting an already-enabled tool
     *     is a no-op that still returns 200.
     */
    post: operations["grant_tool_v1_personas__persona_id__tools_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Persona
     * @description Get a persona's YAML + metadata (404 if not the caller's).
     */
    get: operations["get_persona_v1_personas__persona_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Persona
     * @description Delete a persona + all its conversations and memory (cascade).
     */
    delete: operations["delete_persona_v1_personas__persona_id__delete"];
    options?: never;
    head?: never;
    /**
     * Update Persona
     * @description Replace a persona's YAML (re-validated) and re-index its memory.
     */
    patch: operations["update_persona_v1_personas__persona_id__patch"];
    trace?: never;
  };
  "/v1/personas/{persona_id}/consent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Set Consent
     * @description Set the persona's auto-dispatch consent (grant / decline / revoke).
     *
     *     Spec 21 T09 (D-21-2/7/8): only this ``user``-sourced settings write may
     *     change consent; ``persona_self`` never can. Each transition stamps
     *     ``consent_updated_at`` and emits an ``AuditEvent`` naming the transition.
     */
    patch: operations["set_consent_v1_personas__persona_id__consent_patch"];
    trace?: never;
  };
  "/v1/personas/{persona_id}/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Conversation
     * @description Start a new conversation against a persona.
     */
    post: operations["create_conversation_v1_personas__persona_id__conversations_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/conversations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Conversations
     * @description List the caller's conversations (paginated; RLS-scoped).
     */
    get: operations["list_conversations_v1_conversations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/conversations/{conversation_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Conversation
     * @description Get a conversation's full message history (404 if not the caller's).
     */
    get: operations["get_conversation_v1_conversations__conversation_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Conversation
     * @description Delete a conversation + all its messages + workspace artefacts.
     *
     *     Cascade reach (T19 + Spec 13 T12 co-landing per D-14-X-cascade-coordination):
     *
     *     1. DB rows (existing): the ``conversations`` row + its ``messages`` /
     *        ``turn_logs`` via FK cascade.
     *     2. **Document workspace + DocumentStore chunks** (T19): every doc
     *        attached to the conversation, via
     *        :func:`document_service.remove_all_for_conversation` — the
     *        cascade-helper T13 introduced specifically for this reuse.
     *     3. **Image workspace files** (Spec 13 T12): each image referenced by
     *        the conversation's messages. Spec 13 owns this branch; the two
     *        cascade extensions coexist additively in this same handler per
     *        the D-14-X-cascade-coordination locking decision.
     *
     *     404 if not the caller's conversation (RLS-scoped).
     */
    delete: operations["delete_conversation_v1_conversations__conversation_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/conversations/{conversation_id}/messages": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Post Message
     * @description Send a message; stream the response as SSE (§5.2, KEYSTONE 1).
     *
     *     Multimodal (spec 13 T20): when ``body.images`` is non-empty the route
     *     constructs a multimodal :class:`ConversationMessage` content list
     *     (``[TextContent, ImageContent, ...]``) and passes ``turn_has_image=True``
     *     through to the runtime so :meth:`Router.choose` restricts to vision-capable
     *     tiers. The text-only path (``body.images is None``) is unchanged
     *     byte-for-byte — T03/T13 regression invariants hold.
     */
    post: operations["post_message_v1_conversations__conversation_id__messages_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}/runs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Run
     * @description Start an agentic run (returns the run_id immediately; runs in background).
     */
    post: operations["start_run_v1_personas__persona_id__runs_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/runs/{run_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Run
     * @description Get a run's status + accumulated steps (RLS-scoped → 404).
     */
    get: operations["get_run_v1_runs__run_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/runs/{run_id}/events": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream Events
     * @description Stream the run's events as SSE (live, from the in-process event bus).
     */
    get: operations["stream_events_v1_runs__run_id__events_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/runs/{run_id}/respond": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Respond
     * @description Deliver an answer to a run awaiting an ask-user question.
     */
    post: operations["respond_v1_runs__run_id__respond_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/runs/{run_id}/cancel": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel
     * @description Cancel a running run (stops at the next step boundary → cancelled).
     */
    post: operations["cancel_v1_runs__run_id__cancel_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/credits": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Credits
     * @description The caller's current credit balance (stub counter; §5.5).
     *
     *     ``low_balance`` is surfaced inline so the web app shows the under-limit
     *     warning without a second round-trip (D-11-12).
     */
    get: operations["get_credits_v1_me_credits_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/me/usage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Usage
     * @description The caller's per-turn token usage (§5.5; turn_logs, RLS-scoped).
     */
    get: operations["get_usage_v1_me_usage_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Healthz
     * @description Liveness + DB connectivity check.
     */
    get: operations["healthz_healthz_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/tools": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Tools
     * @description List the available tools (name + description).
     */
    get: operations["list_tools_v1_tools_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/skills": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Skills
     * @description List the available skills (name + description).
     */
    get: operations["list_skills_v1_skills_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/mcp-catalog": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Mcp Catalog
     * @description List the built-in MCP servers (spec 30 T11) for the capability-management UI.
     */
    get: operations["list_mcp_catalog_v1_mcp_catalog_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/conversations/{conversation_id}/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Documents
     * @description List documents attached to a conversation (RLS-scoped; 404 if not the caller's).
     */
    get: operations["list_documents_v1_conversations__conversation_id__documents_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/conversations/{conversation_id}/documents/{doc_ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Document
     * @description Remove a document from a conversation (workspace files + chunks).
     *
     *     Idempotent — removing a non-existent ``doc_ref`` is a no-op (204).
     */
    delete: operations["delete_document_v1_conversations__conversation_id__documents__doc_ref__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}/uploads": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Upload
     * @description Validate + store an upload under the caller's persona.
     *
     *     Dispatches by content-type per CSA-2 + D-14-X-uploads-coordination:
     *
     *     - ``image/*`` (PNG / JPEG / WebP / GIF) → :func:`image_service.upload`
     *       (Spec 13). Returns ``{"workspace_path", "media_type", "size_bytes"}``.
     *     - **Document MIME types** (PDF / DOCX / XLSX / CSV / TXT / MD / code)
     *       → :func:`document_service.upload` (Spec 14). Requires a
     *       ``conversation_id`` form field (documents are conversation-scoped per
     *       Dominant Concern #1; the conversation existence + ownership are
     *       verified via :func:`chat_service.get_conversation`). Returns the
     *       :class:`document_service.DocumentRef` as JSON.
     *     - Anything else → 415 Unsupported Media Type.
     *
     *     Cross-tenant persona id → 404 (persona pre-flight); cross-tenant
     *     conversation_id → 404 (chat_service.get_conversation under RLS).
     *     Validation errors → 422 with structured body. Scanned PDFs raise
     *     :exc:`VisionHandoffRequiredError` → 422 ``"vision_handoff_required"``
     *     (T13 / T21 interim contract — Spec 13 fail-loud at Spec 14's interim
     *     state).
     */
    post: operations["create_upload_v1_personas__persona_id__uploads_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}/uploads/{ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Upload
     * @description Read an uploaded image by its workspace-relative ref.
     *
     *     Cross-tenant access returns 404 by design (existence-disclosure-safe).
     *     Path-traversal attempts (``..``) reject as 404 via the sandbox resolver.
     */
    get: operations["get_upload_v1_personas__persona_id__uploads__ref__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}/imagegen": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Post Imagegen
     * @description Generate one or more images for a persona; persist to workspace; audit.
     *
     *     Returns 201 + an ImageRef-shape payload on success. The bytes land at
     *     ``{workspace_root}/{user_id}/{persona_id}/uploads/{blake2b}.{ext}``
     *     (D-13-4 layout reused per D-15-X-workspace-coordination) and are
     *     fetched via the existing ``GET /v1/personas/:id/uploads/:ref`` route.
     *
     *     Args:
     *         persona_id: Persona id from the path; pre-flight RLS-checked so
     *             cross-tenant ids surface as 404.
     *         body: Validated :class:`ImageGenRequest` (Pydantic 422 on shape
     *             violations before we get here).
     *         request: FastAPI request — used for ``app.state`` access to the
     *             RLS engine, the workspace root, and the composed image backend.
     *         user: Authenticated principal from the bearer token.
     *
     *     Returns:
     *         ImageRef-shape JSON payload (mirrors the Spec 13 upload response
     *         but as a list since ``count`` can be 2).
     *
     *     Raises:
     *         ImageGenUnavailableError: The provider is not configured at all
     *             (no ``PERSONA_IMAGEGEN_API_KEY`` at startup) → 503 via the
     *             app exception handler.
     *         HTTPException: 502 for upstream provider failures; 422 for
     *             content rejection (provider moderation or hard-line filter);
     *             403 for ``ToolNotAllowedError``; 404 for cross-tenant; 402 for
     *             credits exhaustion; 429 for concurrency cap or rate limit.
     */
    post: operations["post_imagegen_v1_personas__persona_id__imagegen_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}/artifacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Artifacts
     * @description List the persona's workspace artifacts (D-F5-1).
     *
     *     - Walks ``workspace_root/<owner_id>/<persona_id>/**`` for non-sidecar
     *       files; reads ``.meta.json`` sidecars where present.
     *     - Filters by source / type / conversation_id / q (all optional).
     *     - Sorts by ``created_at`` DESC, paginates by ``offset``/``limit``.
     *     - ``limit`` is hard-capped at 200 via Pydantic ``Query(le=200)`` —
     *       requesting more returns ``422`` with a structured error (NOT silent
     *       truncation), per D-F5-X-artifact-list-pagination.
     *
     *     Cross-tenant persona ids return 404 via the pre-flight RLS check.
     */
    get: operations["list_artifacts_v1_personas__persona_id__artifacts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}/artifacts/{ref}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Artifact
     * @description Delete a workspace artifact (bytes + sidecar) per D-F5-X-artifact-delete-shape.
     *
     *     Atomic invariant: bytes deleted BEFORE sidecar. A failure at the sidecar
     *     step surfaces 500 with structured detail so the operator can investigate;
     *     the bytes are already gone (ghost-sidecar state is recoverable).
     *
     *     Cross-tenant persona ids return 404 via the pre-flight RLS check.
     */
    delete: operations["delete_artifact_v1_personas__persona_id__artifacts__ref__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/mcp-servers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Mcp Servers
     * @description List the caller's BYO MCP servers (credential redacted).
     */
    get: operations["list_mcp_servers_v1_mcp_servers_get"];
    put?: never;
    /**
     * Create Mcp Server
     * @description Add a bring-your-own MCP server (SSRF-validated; credential encrypted).
     */
    post: operations["create_mcp_server_v1_mcp_servers_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/mcp-servers/{server_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Mcp Server
     * @description Get one BYO MCP server (RLS-scoped → 404).
     */
    get: operations["get_mcp_server_v1_mcp_servers__server_id__get"];
    put?: never;
    post?: never;
    /**
     * Delete Mcp Server
     * @description Delete a BYO MCP server (assignments cascade; RLS-scoped → 404).
     */
    delete: operations["delete_mcp_server_v1_mcp_servers__server_id__delete"];
    options?: never;
    head?: never;
    /**
     * Update Mcp Server
     * @description Patch a BYO MCP server (re-validates a new URL; re-encrypts credentials).
     */
    patch: operations["update_mcp_server_v1_mcp_servers__server_id__patch"];
    trace?: never;
  };
  "/v1/mcp-servers/{server_id}/test": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Check Mcp Server Connection
     * @description Test-connect to the server (SSRF-pinned) and discover its tools (D-30-5).
     */
    post: operations["check_mcp_server_connection_v1_mcp_servers__server_id__test_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}/mcp-servers": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Persona Mcp Servers
     * @description List the BYO MCP servers assigned to a persona (RLS-scoped).
     */
    get: operations["list_persona_mcp_servers_v1_personas__persona_id__mcp_servers_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/v1/personas/{persona_id}/mcp-servers/{server_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Assign Mcp Server
     * @description Assign a BYO MCP server to a persona (D-30-6; idempotent; RLS both ends).
     */
    put: operations["assign_mcp_server_v1_personas__persona_id__mcp_servers__server_id__put"];
    post?: never;
    /**
     * Unassign Mcp Server
     * @description Remove a persona↔server assignment (idempotent; RLS-scoped).
     */
    delete: operations["unassign_mcp_server_v1_personas__persona_id__mcp_servers__server_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ArtifactItem
     * @description A single workspace artifact in the F5 list view.
     *
     *     The ``ref`` is the workspace-relative path the existing
     *     ``GET /v1/personas/{id}/uploads/{ref}`` route already knows how to
     *     serve — F5 reuses that route for downloads + inline rendering.
     */
    ArtifactItem: {
      /** Ref */
      ref: string;
      /** Size Bytes */
      size_bytes: number;
      /** Media Type */
      media_type: string;
      metadata?: components["schemas"]["ArtifactMetadataView"] | null;
    };
    /**
     * ArtifactListResponse
     * @description Paginated artifact-list response for D-F5-1.
     *
     *     ``total`` is the post-filter count; ``items`` is the window of size
     *     ``limit`` starting at ``offset``. The client computes ``hasMore`` from
     *     ``offset + items.length < total``.
     */
    ArtifactListResponse: {
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Items */
      items: components["schemas"]["ArtifactItem"][];
    };
    /**
     * ArtifactMetadataView
     * @description Sidecar metadata surfaced through the artifact list endpoint.
     *
     *     Mirrors ``services.artifact_metadata.WorkspaceArtifactMetadata`` at the
     *     API surface. Kept as a distinct response model (rather than re-exporting
     *     the service shape) so the OpenAPI schema is self-contained and the
     *     web client gets stable types.
     */
    ArtifactMetadataView: {
      /** Source */
      source: string;
      /** Type */
      type: string;
      /** Producing Spec */
      producing_spec: string;
      /** Conversation Id */
      conversation_id: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Original Name */
      original_name: string | null;
    };
    /**
     * AuthorPersonaRequest
     * @description LLM-assisted authoring from a natural-language description (§5.1, §6.3).
     */
    AuthorPersonaRequest: {
      /** Description */
      description: string;
    };
    /**
     * AuthoringDraft
     * @description The draft envelope returned by ``/author`` and ``/author/refine`` (D-10-2).
     *
     *     A draft is NOT a persona row — the user reviews/refines it, then saves via
     *     ``POST /v1/personas`` (which creates the row). ``errors`` is populated only
     *     when validation retries are exhausted (best-effort YAML returned for the form
     *     to fix, §3.3); ``None`` on success.
     */
    AuthoringDraft: {
      /** Yaml */
      yaml: string;
      /** Questions */
      questions?: components["schemas"]["ClarifyingQuestion"][];
      /** Prompt Version */
      prompt_version: string;
      /** Errors */
      errors?: string[] | null;
    };
    /** Body_create_upload_v1_personas__persona_id__uploads_post */
    Body_create_upload_v1_personas__persona_id__uploads_post: {
      /** File */
      file: string;
      /** Conversation Id */
      conversation_id?: string | null;
    };
    /**
     * ChannelContext
     * @description Opaque connector context passed through the chat endpoint (D-08-3).
     *
     *     The API stores this on the message row and never interprets it — ``platform``
     *     is a free-form string, NEVER an enum the API branches on. All connector logic
     *     lives in the future spec-12 connectors. Null/absent is the web-UI case.
     */
    ChannelContext: {
      /** Platform */
      platform: string;
      /** Platform User Id */
      platform_user_id?: string | null;
      /** Platform Chat Id */
      platform_chat_id?: string | null;
      /** Metadata */
      metadata?: {
        [key: string]: string;
      };
    };
    /**
     * ClarifyingQuestion
     * @description One suggested question the user can answer to improve a draft persona.
     *
     *     ``section`` is a free-form hint (expected: identity | self_facts | worldview
     *     | constraints | tools | skills) — NOT an enum, so a model that names a
     *     section we don't anticipate doesn't sink the parse.
     */
    ClarifyingQuestion: {
      /** Section */
      section: string;
      /** Question */
      question: string;
    };
    /**
     * ConversationDetail
     * @description Full conversation history.
     */
    ConversationDetail: {
      /** Id */
      id: string;
      /** Persona Id */
      persona_id: string;
      /** Title */
      title: string;
      /** Messages */
      messages: components["schemas"]["MessageView"][];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * ConversationSummary
     * @description A conversation in a list view.
     *
     *     The two ``last_message_*`` fields let the sidebar render a real preview of
     *     the most recent turn instead of falling back to the title. They are
     *     populated in a single set-based LIST query (a ``ROW_NUMBER()`` window over
     *     the RLS-scoped ``messages`` rows — no per-row fan-out) and are ``None`` for
     *     a conversation that has no messages yet.
     *
     *     Attributes:
     *         id: The conversation id.
     *         persona_id: The persona this conversation belongs to.
     *         title: The conversation's display title.
     *         created_at: Creation timestamp (UTC-aware).
     *         updated_at: Last-activity timestamp (UTC-aware); list order is by this
     *             field descending.
     *         last_message_preview: The most recent message's text, trimmed and
     *             truncated server-side to :data:`LAST_MESSAGE_PREVIEW_MAX_LEN`
     *             characters (an ellipsis replaces the tail when it overflows).
     *             ``None`` when the conversation has no messages.
     *         last_message_role: Speaker role of the most recent message, using the
     *             existing message-role vocabulary (``user`` is the human; every
     *             other role is the persona/assistant side). ``None`` when the
     *             conversation has no messages. The UI switches on this to attribute
     *             the preview ("You: …" vs the persona).
     */
    ConversationSummary: {
      /** Id */
      id: string;
      /** Persona Id */
      persona_id: string;
      /** Title */
      title: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** Last Message Preview */
      last_message_preview?: string | null;
      /** Last Message Role */
      last_message_role?: ("user" | "assistant" | "system" | "tool") | null;
    };
    /**
     * CreateConversationRequest
     * @description Start a new conversation against a persona.
     */
    CreateConversationRequest: {
      /**
       * Title
       * @default
       */
      title: string;
    };
    /**
     * CreateMCPServerRequest
     * @description Add a bring-your-own MCP server (spec 30, D-30-3/4).
     *
     *     ``url`` is SSRF-validated (https-only, public target) at the route AND on
     *     every live connect. ``credential`` (a bearer token for ``auth_method =
     *     "bearer"``) is encrypted at rest (T07) and NEVER returned or logged; it is
     *     required when ``auth_method`` is not ``"none"``.
     */
    CreateMCPServerRequest: {
      /** Name */
      name: string;
      /** Url */
      url: string;
      /**
       * Auth Method
       * @default none
       * @enum {string}
       */
      auth_method: "none" | "bearer";
      /** Credential */
      credential?: string | null;
    };
    /**
     * CreatePersonaRequest
     * @description Create a persona from a YAML document (validated against the v1.0 schema).
     *
     *     ``avatar_url`` is an optional presentation field (not part of the YAML
     *     schema) — the persona-list / chat-header visual identity.
     */
    CreatePersonaRequest: {
      /** Yaml */
      yaml: string;
      /** Avatar Url */
      avatar_url?: string | null;
    };
    /**
     * CreditsResponse
     * @description The user's current credit balance (stub counter).
     *
     *     ``low_balance`` is True when the balance is below
     *     :data:`credits_service.LOW_BALANCE_THRESHOLD` (10 000 by default) — the web
     *     app uses it to surface the under-limit warning (D-11-12).
     */
    CreditsResponse: {
      /** Balance */
      balance: number;
      /**
       * Low Balance
       * @default false
       */
      low_balance: boolean;
    };
    /**
     * DocumentRef
     * @description Reference to an attached document — the API-boundary type.
     *
     *     Persisted alongside the original file as a ``{doc_ref}.meta.json``
     *     sidecar in the workspace. Returned by :func:`upload`,
     *     :func:`list_for_conversation`, and (via JSON) the API GET endpoint
     *     (T18). Carries the metadata T14/T15/T16 need to render the prompt
     *     sections + the synopsis.
     */
    DocumentRef: {
      /** Doc Ref */
      doc_ref: string;
      /** Filename */
      filename: string;
      /** Title */
      title: string;
      /** Format */
      format: string;
      /** Workspace Path */
      workspace_path: string;
      strategy: components["schemas"]["IngestStrategy"];
      /** Token Count */
      token_count: number;
      /** Page Count */
      page_count?: number | null;
      /** Sheet Names */
      sheet_names?: string[] | null;
      /** Size Bytes */
      size_bytes?: number | null;
      /**
       * Images
       * @default []
       */
      images: components["schemas"]["ImageContent"][];
    };
    /**
     * GrantToolRequest
     * @description Enable a tool on a persona's allow-list via runtime consent (spec 26 T11).
     *
     *     Sent when the user accepts a runtime tool-gap offer. ``turn_index`` is the
     *     conversation turn the offer came from (recorded in the persona_self audit).
     */
    GrantToolRequest: {
      /** Tool Name */
      tool_name: string;
      /** Turn Index */
      turn_index?: number | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * ImageContent
     * @description An image *reference* block within a multimodal message ``content`` list.
     *
     *     Per Spec 13 D-13-X-now option (c), the message store carries only the
     *     workspace reference — image bytes live exactly once under the persona's
     *     Spec 03 workspace and are resolved at send time by the backend
     *     serialisers (Spec 13 T05/T06). This is the structural guard behind
     *     Dominant Concern #2: the ``messages`` table size grows with reference
     *     count, not with image bytes. See
     *     ``docs/specs/phase2/spec_13/decisions.md`` (D-13-X-now) and the T13
     *     store-by-reference regression test.
     *
     *     Attributes:
     *         type: Discriminator tag — always the literal ``"image"`` so the
     *             :data:`MessageContent` tagged union can resolve this block by
     *             its ``type`` field on deserialisation.
     *         workspace_path: The reference into the persona workspace (Spec 03).
     *             Resolved to bytes only at backend-send time; the message store
     *             never holds the bytes themselves.
     *         media_type: One of the four supported image MIME types per
     *             **D-13-3**: ``image/png``, ``image/jpeg``, ``image/webp``,
     *             ``image/gif``. Any other value is rejected at validation time.
     */
    ImageContent: {
      /**
       * Type
       * @default image
       * @constant
       */
      type: "image";
      /** Workspace Path */
      workspace_path: string;
      /**
       * Media Type
       * @enum {string}
       */
      media_type: "image/png" | "image/jpeg" | "image/webp" | "image/gif";
    };
    /**
     * ImageGenRequest
     * @description Body of ``POST /v1/personas/:id/imagegen``.
     *
     *     The closed Literal surface on ``size`` and ``quality`` ensures invalid
     *     values land as 422 Pydantic validation errors before any service-
     *     layer work happens; ``count`` is bounded by D-15-3 (``le=2``).
     *
     *     Attributes:
     *         prompt: The user-supplied text prompt. Required, min length 1.
     *             The visual_style merge runs at the service layer
     *             (:func:`persona_api.imagegen.service.generate`) so the prompt
     *             here is the raw user input — NOT yet merged.
     *         size: One of the three closed presets per D-15-3. Defaults to
     *             ``"1024x1024"``. The OpenAI backend rounds non-square presets
     *             per D-15-X-size-rounding; the audit captures the REQUESTED
     *             value (this field's literal), not the rounded one.
     *         count: Number of images to generate. ``Field(ge=1, le=2)`` enforces
     *             the D-15-3 cap. Defaults to 1.
     *         quality: One of the two closed presets per D-15-3. Defaults to
     *             ``"standard"``.
     */
    ImageGenRequest: {
      /** Prompt */
      prompt: string;
      /**
       * Size
       * @default 1024x1024
       * @enum {string}
       */
      size: "1024x1024" | "1024x1792" | "1792x1024";
      /**
       * Count
       * @default 1
       */
      count: number;
      /**
       * Quality
       * @default standard
       * @enum {string}
       */
      quality: "standard" | "high";
    };
    /**
     * ImageRef
     * @description Image reference carried on a chat message (spec 13, D-13-X-now option c).
     *
     *     Refers to a previously-uploaded image in the persona's workspace (Spec 03).
     *     Image bytes live exactly once in the workspace; the chat body and the
     *     persisted ``messages`` row carry only ``workspace_path`` + ``media_type``
     *     so storage scales with reference count, not with image bytes.
     *
     *     Attributes:
     *         workspace_path: Workspace-relative path returned by the uploads route
     *             (``uploads/<ref>.<ext>``). Resolved against
     *             ``workspace_root/owner_id/persona_id`` at backend send time.
     *         media_type: One of the four supported image MIME types per D-13-3:
     *             ``image/png``, ``image/jpeg``, ``image/webp``, ``image/gif``.
     *             Any other value is rejected at validation time.
     */
    ImageRef: {
      /** Workspace Path */
      workspace_path: string;
      /**
       * Media Type
       * @enum {string}
       */
      media_type: "image/png" | "image/jpeg" | "image/webp" | "image/gif";
    };
    /**
     * IngestStrategy
     * @description The ingestion paths a document can take.
     *
     *     ``VISION_HANDOFF_REQUIRED`` is what :func:`ingest_document` returns when
     *     the parser sets ``needs_vision_handoff=True`` — the caller (T13's
     *     :func:`persona_api.services.document_service.upload`) detects this and
     *     performs the actual rasterisation + ImageContent creation (T21). The
     *     caller-side outcome ``VISION_HANDOFF`` records the completed handoff
     *     on the persisted :class:`DocumentRef`.
     * @enum {string}
     */
    IngestStrategy:
      | "whole_inject"
      | "retrieval"
      | "vision_handoff_required"
      | "vision_handoff";
    /**
     * MCPCatalogServer
     * @description A built-in MCP server in the management catalog (spec 30 T11).
     *
     *     A persona enables a server by adding ``mcp:<name>`` to its ``tools``
     *     allow-list. ``provider`` is the recommender tag (``mcp:builtin`` /
     *     ``mcp:optional``); ``required_env`` lists env vars an operator must set.
     */
    MCPCatalogServer: {
      /** Name */
      name: string;
      /** Description */
      description: string;
      /** Provider */
      provider: string;
      /** Default Enabled */
      default_enabled: boolean;
      /** Required Env */
      required_env?: string[];
    };
    /**
     * MCPServerDetail
     * @description A bring-your-own MCP server as returned to its owner (spec 30, D-30-3).
     *
     *     The credential is NEVER included — only ``has_credential`` (whether one is
     *     stored). ``discovered_tools`` is the cached eager-discovery result (D-30-5),
     *     ``None`` until a successful test-connection.
     */
    MCPServerDetail: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Url */
      url: string;
      /** Auth Method */
      auth_method: string;
      /** Enabled */
      enabled: boolean;
      /** Has Credential */
      has_credential: boolean;
      /** Discovered Tools */
      discovered_tools?: string[] | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * MCPServerTestResult
     * @description Outcome of a BYO-MCP test-connection (spec 30, D-30-5).
     *
     *     ``ok`` true → ``tools`` lists the discovered tool names (cached on the row).
     *     ``ok`` false → ``error`` is a short, non-sensitive reason category.
     */
    MCPServerTestResult: {
      /** Ok */
      ok: boolean;
      /** Tools */
      tools?: string[];
      /** Error */
      error?: string | null;
    };
    /**
     * MessageView
     * @description A single message in a conversation history.
     */
    MessageView: {
      /** Id */
      id: string;
      /** Role */
      role: string;
      /** Content */
      content: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Channel */
      channel?: {
        [key: string]: unknown;
      } | null;
      /** Tier Used */
      tier_used?: string | null;
    };
    /**
     * PersonaCapabilities
     * @description Deployment-derived capability flags surfaced with the persona detail.
     *
     *     Hydrated from the runtime :class:`persona_runtime.tier.TierRegistry` so the
     *     UI can answer "does this persona support image attachments?" BEFORE the
     *     user attempts to send (Spec 13 fail-loud made visible — Spec F3 §10 #7;
     *     D-F3-X-no-vision-surface-shape). At v0.1 the answer is deployment-wide:
     *     every persona under a given deployment shares the same registry, so
     *     ``vision`` is identical across personas — see D-F3-X-deployment-vs-persona-
     *     capability-framing. The field's shape survives the v0.2 inflection where
     *     per-persona tier pins make the answer genuinely per-persona; only the
     *     hydration source changes (from registry to per-persona lookup).
     *
     *     Attributes:
     *         vision: ``True`` iff at least one configured tier resolves to a
     *             backend whose ``supports_vision`` is ``True``. Read via the
     *             public :meth:`TierRegistry.supports_vision_for` method
     *             (D-F3-X-tier-registry-public-contract).
     *         configured_tiers: Tier names registered on the active deployment
     *             in insertion order (``("small", "mid", "frontier")`` for the
     *             typical three-tier deployment). The UI may surface these in a
     *             disabled-attach tooltip to explain *which* models the deployment
     *             has configured.
     */
    PersonaCapabilities: {
      /** Vision */
      vision: boolean;
      /** Configured Tiers */
      configured_tiers: string[];
    };
    /**
     * PersonaDetail
     * @description A persona's full detail (YAML + metadata).
     *
     *     The optional :attr:`capabilities` field (D-F3-X-capability-endpoint) is
     *     additive on top of the Spec 08 / Spec 09 surface: tests + composition
     *     roots that do not wire a :class:`TierRegistry` (e.g. unit fixtures
     *     without the runtime) omit the field and the API returns ``None`` so the
     *     persona-detail surface stays usable without runtime composition.
     */
    PersonaDetail: {
      /** Id */
      id: string;
      /** Yaml */
      yaml: string;
      /** Schema Version */
      schema_version: string;
      /** Avatar Url */
      avatar_url?: string | null;
      capabilities?: components["schemas"]["PersonaCapabilities"] | null;
      /** Consent To Auto Dispatch */
      consent_to_auto_dispatch?: boolean | null;
      /** Consent Updated At */
      consent_updated_at?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * PersonaSummary
     * @description A persona in a list view (no full YAML).
     */
    PersonaSummary: {
      /** Id */
      id: string;
      /** Name */
      name: string;
      /** Role */
      role: string;
      /** Avatar Url */
      avatar_url?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /**
     * PostMessageRequest
     * @description Send a user message; the response streams over SSE (§5.2).
     *
     *     ``channel`` is the optional connector passthrough (D-08-3) — null for the
     *     web UI. The runtime ignores it in v0.1; the API just stores it on the
     *     message row and echoes ``format_hints`` on the ``done`` event.
     *
     *     ``images`` is the optional spec-13 multimodal extension (D-13-X-now option
     *     c, D-13-5): up to 4 :class:`ImageRef` per message. ``None`` (the default)
     *     keeps the text-only path byte-for-byte unchanged. An empty list is
     *     equivalent to ``None`` semantically but rejected as a validation error so
     *     callers don't accidentally send ``images=[]`` and skip the cap check; pass
     *     ``None`` or omit the field.
     *
     *     The cap is enforced via :class:`Field`'s built-in ``min_length`` /
     *     ``max_length`` (D-13-5) so the failure surfaces as a structured
     *     ``too_long`` / ``too_short`` Pydantic v2 error — JSON-serialisable through
     *     the API's ``_request_422`` handler in :mod:`persona_api.errors` (a custom
     *     ``field_validator`` would attach a raw :class:`ValueError` to ``ctx`` and
     *     break the response body's ``json.dumps``).
     */
    PostMessageRequest: {
      /** Content */
      content: string;
      channel?: components["schemas"]["ChannelContext"] | null;
      /** Images */
      images?: components["schemas"]["ImageRef"][] | null;
    };
    /**
     * RefinePersonaRequest
     * @description Refine a draft persona by answering a clarifying question (spec 10, §4 / D-10-2).
     *
     *     Stateless: ``round`` is the count of refinements already applied (the UI owns
     *     the counter); the server rejects ``round > 3`` as the backstop on the
     *     3-round cap (D-10-5).
     */
    RefinePersonaRequest: {
      /** Current Yaml */
      current_yaml: string;
      /** Question */
      question: string;
      /** Answer */
      answer: string;
      /**
       * Round
       * @default 0
       */
      round: number;
    };
    /**
     * RespondToRunRequest
     * @description Answer an ask-user question raised by a running agentic loop (§5.3).
     */
    RespondToRunRequest: {
      /** Answer */
      answer: string;
    };
    /**
     * RunStatusResponse
     * @description A run's status + its accumulated steps (JSON-serialised Run/Step).
     */
    RunStatusResponse: {
      /** Id */
      id: string;
      /** Persona Id */
      persona_id: string;
      /** Task */
      task: string;
      /** Status */
      status: string;
      /** Steps */
      steps?: {
        [key: string]: unknown;
      }[];
      /** Output */
      output?: string | null;
      /** Error */
      error?: string | null;
    };
    /**
     * SetConsentRequest
     * @description Set a persona's auto-dispatch consent (spec 21 T09, D-21-7/2).
     *
     *     ``granted``: ``True`` = grant (auto-dispatch), ``False`` = decline (stable,
     *     no re-prompt), ``None`` = revoke back to "ask" (the settings-toggle OFF
     *     path, which re-arms the prompt on the next autonomous dispatch).
     */
    SetConsentRequest: {
      /** Granted */
      granted?: boolean | null;
    };
    /**
     * StartRunRequest
     * @description Start an agentic run for a task (§5.3).
     */
    StartRunRequest: {
      /** Task */
      task: string;
    };
    /**
     * ToolRecommendation
     * @description One recommended capability for a persona (spec 26 T09 / spec 27 T10).
     *
     *     Spec 27 realises the D-26-10 unification: the same shape now carries a
     *     provider tag so built-in tools, skills, and MCP servers rank together. The
     *     ``provider`` field defaults to ``"builtin"`` so the Spec-26 shape (and its
     *     callers/tests) stay a forward-compatible strict subset.
     *
     *     Attributes:
     *         tool_name: The capability name — a built-in tool name from
     *             ``persona.tools.TOOL_CATALOG``, a skill id, or an ``mcp:<server>``
     *             reference. Hallucinated names are filtered out post-hoc.
     *         rationale: One-line reason the capability fits this persona.
     *         confidence: Recommender confidence in [0, 1]; entries below the floor
     *             are dropped before return.
     *         provider: Where the capability comes from — ``"builtin"`` (tool),
     *             ``"skill"``, ``"mcp:builtin"`` (default-enabled MCP server), or
     *             ``"mcp:optional"`` (opt-in / BYO MCP server). The UI groups by
     *             provider but ranks across all (spec 27 §2.3 / D-27-13).
     */
    ToolRecommendation: {
      /** Tool Name */
      tool_name: string;
      /** Rationale */
      rationale: string;
      /** Confidence */
      confidence: number;
      /**
       * Provider
       * @default builtin
       */
      provider: string;
    };
    /**
     * ToolRecommendationResponse
     * @description The ranked tool-recommendation list returned by ``/personas/recommend-tools``.
     */
    ToolRecommendationResponse: {
      /** Recommendations */
      recommendations?: components["schemas"]["ToolRecommendation"][];
      /** Prompt Version */
      prompt_version: string;
    };
    /**
     * ToolSummary
     * @description A tool or skill name + description (read-only listing).
     */
    ToolSummary: {
      /** Name */
      name: string;
      /** Description */
      description: string;
    };
    /**
     * UpdateMCPServerRequest
     * @description Patch a BYO MCP server (spec 30). All fields optional; omitted = unchanged.
     *
     *     Setting ``credential`` replaces the stored secret (re-encrypted); to clear a
     *     credential, set ``auth_method = "none"``. ``enabled`` toggles the server
     *     without deleting it.
     */
    UpdateMCPServerRequest: {
      /** Name */
      name?: string | null;
      /** Url */
      url?: string | null;
      /** Auth Method */
      auth_method?: ("none" | "bearer") | null;
      /** Credential */
      credential?: string | null;
      /** Enabled */
      enabled?: boolean | null;
    };
    /**
     * UpdatePersonaRequest
     * @description Replace a persona's YAML (re-validated against the v1.0 schema).
     */
    UpdatePersonaRequest: {
      /** Yaml */
      yaml: string;
      /** Avatar Url */
      avatar_url?: string | null;
    };
    /**
     * UsageEntry
     * @description One usage-log row (per-turn telemetry, paginated).
     */
    UsageEntry: {
      /** Persona Id */
      persona_id?: string | null;
      /** Tier Used */
      tier_used: string;
      /** Model Name */
      model_name: string;
      /** Prompt Tokens */
      prompt_tokens: number;
      /** Completion Tokens */
      completion_tokens: number;
      /** Cost Cents */
      cost_cents: number;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_personas_v1_personas_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_persona_v1_personas_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePersonaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  author_persona_v1_personas_author_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthorPersonaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthoringDraft"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refine_persona_v1_personas_author_refine_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RefinePersonaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthoringDraft"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  recommend_tools_v1_personas_recommend_tools_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthorPersonaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ToolRecommendationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  recommend_capabilities_v1_personas_recommend_capabilities_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthorPersonaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ToolRecommendationResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  grant_tool_v1_personas__persona_id__tools_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["GrantToolRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_persona_v1_personas__persona_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_persona_v1_personas__persona_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_persona_v1_personas__persona_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdatePersonaRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  set_consent_v1_personas__persona_id__consent_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SetConsentRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PersonaDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_conversation_v1_personas__persona_id__conversations_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateConversationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationSummary"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_conversations_v1_conversations_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationSummary"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_conversation_v1_conversations__conversation_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ConversationDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_conversation_v1_conversations__conversation_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_message_v1_conversations__conversation_id__messages_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PostMessageRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  start_run_v1_personas__persona_id__runs_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StartRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_run_v1_runs__run_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunStatusResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  stream_events_v1_runs__run_id__events_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  respond_v1_runs__run_id__respond_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RespondToRunRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  cancel_v1_runs__run_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        run_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_credits_v1_me_credits_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CreditsResponse"];
        };
      };
    };
  };
  get_usage_v1_me_usage_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UsageEntry"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  list_tools_v1_tools_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ToolSummary"][];
        };
      };
    };
  };
  list_skills_v1_skills_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ToolSummary"][];
        };
      };
    };
  };
  list_mcp_catalog_v1_mcp_catalog_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MCPCatalogServer"][];
        };
      };
    };
  };
  list_documents_v1_conversations__conversation_id__documents_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["DocumentRef"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_document_v1_conversations__conversation_id__documents__doc_ref__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        conversation_id: string;
        doc_ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_upload_v1_personas__persona_id__uploads_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_create_upload_v1_personas__persona_id__uploads_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_upload_v1_personas__persona_id__uploads__ref__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  post_imagegen_v1_personas__persona_id__imagegen_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImageGenRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_artifacts_v1_personas__persona_id__artifacts_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
        source?: ("upload" | "generated") | null;
        type?: ("image" | "chart" | "doc" | "data" | "diagram") | null;
        conversation_id?: string | null;
        q?: string | null;
      };
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ArtifactListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_artifact_v1_personas__persona_id__artifacts__ref__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
        ref: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_mcp_servers_v1_mcp_servers_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MCPServerDetail"][];
        };
      };
    };
  };
  create_mcp_server_v1_mcp_servers_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMCPServerRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MCPServerDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_mcp_server_v1_mcp_servers__server_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        server_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MCPServerDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_mcp_server_v1_mcp_servers__server_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        server_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_mcp_server_v1_mcp_servers__server_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        server_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMCPServerRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MCPServerDetail"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  check_mcp_server_connection_v1_mcp_servers__server_id__test_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        server_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MCPServerTestResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_persona_mcp_servers_v1_personas__persona_id__mcp_servers_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MCPServerDetail"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  assign_mcp_server_v1_personas__persona_id__mcp_servers__server_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
        server_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  unassign_mcp_server_v1_personas__persona_id__mcp_servers__server_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        persona_id: string;
        server_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
