"""Image upload + fetch integration tests (spec 13 T11).

Drives the real FastAPI app against Docker Postgres with a fake JWT verifier
and the fast HashEmbedder384. The route relies on the spec-08 RLS engine and
the spec-13 image_service for validation/storage; this suite covers the
end-to-end seam:

* Happy path round-trip (POST → GET → bytes match, Content-Type correct).
* Unsupported media type / oversize body / decompression-bomb reject as 422.
* Cross-tenant access returns 404 (existence-disclosure-safe per D-13).
* Path-traversal refs ("..") reject as 404 via the sandbox resolver.
* Rate-limit (D-13-X-rate-limit-bucket: reuse the ``default`` bucket) →
  4th request inside one window returns 429 with the standard rate-limit
  headers (verifies the route honours the existing limiter wiring).
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

import pytest
from fastapi.testclient import TestClient
from persona_api.app import create_app
from persona_api.auth import AuthenticatedUser
from persona_api.config import APIConfig
from persona_api.middleware.rate_limit import InMemoryRateLimitStore, RateLimiter
from persona_api.middleware.rls_context import make_rls_engine
from sqlalchemy import text

if TYPE_CHECKING:
    from collections.abc import Iterator

    from sqlalchemy import Engine
    from tests.conftest import HashEmbedder384

pytestmark = pytest.mark.integration


_VALID_YAML = """\
schema_version: "1.0"
identity:
  name: Astrid
  role: Norwegian tenancy law assistant
  background: |
    Helps tenants understand husleieloven.
  language_default: en
  constraints: []
"""


# Minimum-valid 1x1 RGB PNG (generated by Pillow; deterministic 69-byte payload).
# We use a real-encoded PNG so it survives Pillow's downscale path (T10b) — a
# hand-rolled IDAT is hard to make zlib-valid by inspection.
_TINY_PNG: bytes = bytes.fromhex(
    "89504e470d0a1a0a0000000d4948445200000001000000010802000000907753de"
    "0000000c49444154789c63f8cfc0000003010100c9fe92ef0000000049454e44ae"
    "426082"
)


@pytest.fixture
def client(
    migrated_engine: Engine,  # noqa: ARG001 — ensures schema + grants
    embedder: HashEmbedder384,
    tmp_path: Path,
) -> Iterator[tuple[TestClient, str, str, Path]]:
    """Real FastAPI client wired to Docker Postgres + a workspace under tmp_path.

    Seeds two users (user_A + user_B) for the cross-tenant tests; yields the
    client, user_A id, user_B id, and the workspace_root path so tests can
    inspect on-disk artefacts.
    """
    import os

    app_url = os.environ.get("APP_DATABASE_URL")
    if not app_url:
        pytest.skip("APP_DATABASE_URL not set")

    workspace_root = tmp_path / "workspace"
    cfg = APIConfig(
        app_database_url=app_url,
        audit_root=str(tmp_path / "audit"),
        workspace_root=workspace_root,
    )
    app = create_app(cfg)

    async def _fake_verify(token: str) -> AuthenticatedUser:
        return AuthenticatedUser(id=token, email=None)

    user_a, user_b = "user_t11_a", "user_t11_b"
    with TestClient(app) as c:
        app.state.verify_token = _fake_verify
        app.state.embedder = embedder
        # Drop the lifespan-installed TierRegistry so the persona-detail
        # capabilities surface doesn't lazily instantiate a real chat backend
        # (AuthenticationError("missing API key") on CI without ANTHROPIC_API_KEY).
        if hasattr(app.state, "tier_registry"):
            app.state.tier_registry = None
        # Seed both users as superuser (FK target for personas.owner_id).
        su = make_rls_engine(os.environ["DATABASE_URL"])
        with su.begin() as conn:
            for u in (user_a, user_b):
                conn.execute(
                    text("INSERT INTO users (id, email) VALUES (:i, :e) ON CONFLICT DO NOTHING"),
                    {"i": u, "e": f"{u}@x.test"},
                )
        su.dispose()
        yield c, user_a, user_b, workspace_root
        # Cleanup
        su = make_rls_engine(os.environ["DATABASE_URL"])
        with su.begin() as conn:
            conn.execute(
                text("DELETE FROM users WHERE id IN (:a, :b)"),
                {"a": user_a, "b": user_b},
            )
        su.dispose()


def _auth(user_id: str) -> dict[str, str]:
    return {"Authorization": f"Bearer {user_id}"}


def _create_persona(c: TestClient, user_id: str) -> str:
    resp = c.post("/v1/personas", json={"yaml": _VALID_YAML}, headers=_auth(user_id))
    assert resp.status_code == 201, resp.text
    return str(resp.json()["id"])


def _load_bomb(name: str) -> bytes:
    """Read a T10a decompression-bomb fixture from disk."""
    root = Path(__file__).resolve().parents[1] / "fixtures" / name
    return root.read_bytes()


def test_upload_roundtrip(client: tuple[TestClient, str, str, Path]) -> None:
    c, uid_a, _uid_b, workspace_root = client
    pid = _create_persona(c, uid_a)

    # POST a valid 1x1 PNG.
    resp = c.post(
        f"/v1/personas/{pid}/uploads",
        files={"file": ("tiny.png", _TINY_PNG, "image/png")},
        headers=_auth(uid_a),
    )
    assert resp.status_code == 201, resp.text
    body = resp.json()
    assert body["media_type"] == "image/png"
    assert body["size_bytes"] > 0
    assert body["workspace_path"].startswith("uploads/")
    ref = body["workspace_path"]

    # File was actually written to the workspace.
    stored = workspace_root / uid_a / pid / ref
    assert stored.is_file(), f"expected file at {stored}"

    # GET the ref; bytes match, Content-Type matches.
    resp = c.get(f"/v1/personas/{pid}/uploads/{ref}", headers=_auth(uid_a))
    assert resp.status_code == 200, resp.text
    assert resp.headers["content-type"].startswith("image/png")
    assert resp.content == stored.read_bytes()


def test_unsupported_format_returns_422(client: tuple[TestClient, str, str, Path]) -> None:
    c, uid_a, _uid_b, _ws = client
    pid = _create_persona(c, uid_a)
    resp = c.post(
        f"/v1/personas/{pid}/uploads",
        files={"file": ("doc.tiff", b"II*\x00garbage", "image/tiff")},
        headers=_auth(uid_a),
    )
    assert resp.status_code == 422, resp.text
    body = resp.json()
    # Body shape: {"detail": {"error": "image_validation_error", ...}}
    detail = body["detail"]
    assert detail["context"]["reason"] == "unsupported_media_type"


def test_oversize_returns_422(client: tuple[TestClient, str, str, Path]) -> None:
    c, uid_a, _uid_b, _ws = client
    pid = _create_persona(c, uid_a)
    # 21 MB > 20 MB cap. Body starts with PNG signature so the media-type gate
    # passes and we hit the size gate.
    huge = _TINY_PNG + b"\x00" * (21 * 1024 * 1024)
    resp = c.post(
        f"/v1/personas/{pid}/uploads",
        files={"file": ("big.png", huge, "image/png")},
        headers=_auth(uid_a),
    )
    assert resp.status_code == 422, resp.text
    assert resp.json()["detail"]["context"]["reason"] == "oversize"


def test_decompression_bomb_returns_422(client: tuple[TestClient, str, str, Path]) -> None:
    c, uid_a, _uid_b, _ws = client
    pid = _create_persona(c, uid_a)
    bomb = _load_bomb("decompression_bomb.png")
    resp = c.post(
        f"/v1/personas/{pid}/uploads",
        files={"file": ("bomb.png", bomb, "image/png")},
        headers=_auth(uid_a),
    )
    assert resp.status_code == 422, resp.text
    assert resp.json()["detail"]["context"]["reason"] == "decompression_bomb"


def test_cross_tenant_get_returns_404(client: tuple[TestClient, str, str, Path]) -> None:
    c, uid_a, uid_b, _ws = client
    pid = _create_persona(c, uid_a)
    # User A uploads.
    resp = c.post(
        f"/v1/personas/{pid}/uploads",
        files={"file": ("tiny.png", _TINY_PNG, "image/png")},
        headers=_auth(uid_a),
    )
    assert resp.status_code == 201
    ref = resp.json()["workspace_path"]
    # User B GETs A's ref on A's persona → pre-flight RLS rejects (404).
    resp = c.get(f"/v1/personas/{pid}/uploads/{ref}", headers=_auth(uid_b))
    assert resp.status_code == 404


def test_cross_tenant_post_returns_404(client: tuple[TestClient, str, str, Path]) -> None:
    c, uid_a, uid_b, _ws = client
    pid = _create_persona(c, uid_a)
    # User B tries to POST to A's persona id → pre-flight RLS rejects (404).
    resp = c.post(
        f"/v1/personas/{pid}/uploads",
        files={"file": ("tiny.png", _TINY_PNG, "image/png")},
        headers=_auth(uid_b),
    )
    assert resp.status_code == 404


def test_traversal_attempts_blocked(client: tuple[TestClient, str, str, Path]) -> None:
    c, uid_a, _uid_b, _ws = client
    pid = _create_persona(c, uid_a)
    # Traversal ref ("..") rejects as 404 via the sandbox resolver.
    resp = c.get(
        f"/v1/personas/{pid}/uploads/uploads/..%2F..%2Fetc%2Fpasswd",
        headers=_auth(uid_a),
    )
    assert resp.status_code == 404


def test_rate_limit_returns_429(client: tuple[TestClient, str, str, Path]) -> None:
    c, uid_a, _uid_b, _ws = client
    pid = _create_persona(c, uid_a)
    # Override the limiter to a tiny limit so the 4th call trips it.
    c.app.state.rate_limiter = RateLimiter(
        InMemoryRateLimitStore(), default_limit=3, per_endpoint={}
    )
    for _ in range(3):
        resp = c.post(
            f"/v1/personas/{pid}/uploads",
            files={"file": ("t.png", _TINY_PNG, "image/png")},
            headers=_auth(uid_a),
        )
        assert resp.status_code == 201, resp.text
    # 4th call → 429 + the standard rate-limit headers.
    resp = c.post(
        f"/v1/personas/{pid}/uploads",
        files={"file": ("t.png", _TINY_PNG, "image/png")},
        headers=_auth(uid_a),
    )
    assert resp.status_code == 429, resp.text
    assert resp.headers["X-RateLimit-Limit"] == "3"
    assert resp.headers["X-RateLimit-Remaining"] == "0"
    assert "X-RateLimit-Reset" in resp.headers
    assert "Retry-After" in resp.headers
