"""Domain exceptions for the image generation layer.

Every error raised by a :class:`persona.imagegen.protocol.ImageBackend`
implementation, by the categorical hard-line filter
(:mod:`persona.imagegen.safety`), or by the ``generate_image`` tool factory
is a subclass of :class:`ImageGenError`, which in turn is a subclass of
:class:`persona.errors.PersonaError`. Provider-specific exceptions from
third-party SDKs (``openai``, ``fal_client``, ``httpx``) are caught at the
adapter boundary and re-raised through this hierarchy so callers depend on
our types rather than on a transitive dependency.

This mirrors the :mod:`persona.backends.errors` shape; see
``docs/specs/phase2/spec_15/decisions.md`` gate paragraph #1 (Spec 02
mirror discipline) and the D-15-X-* leans for the rationale.
"""

from __future__ import annotations

from persona.errors import PersonaError

__all__ = [
    "ContentRejectedError",
    "ImageGenError",
    "ImageGenUnavailableError",
    "ImageProviderError",
]


class ImageGenError(PersonaError):
    """Base for every image-generation-raised error.

    Non-retryable by default. Subclasses signal specific failure modes
    (:class:`ImageGenUnavailableError` for missing/invalid credentials;
    :class:`ImageProviderError` for transient/rate-limit/unsupported-option
    provider failures; :class:`ContentRejectedError` for moderation /
    safety rejections from either provider moderation or the categorical
    hard-line filter).

    Implementations should always populate ``context`` with at least
    ``provider`` and (when known) ``model`` so log messages are structured.
    """


class ImageGenUnavailableError(ImageGenError):
    """Raised when an image backend cannot be used at all.

    Fired by concrete backend ``__init__`` methods when the configured API
    key is missing or empty (fail fast — D-15-X-pydantic-boundary-types
    plus the Spec 02 D-02-* construction-time-fail-fast precedent), and
    at call time when the provider returns 401 / 403 or otherwise rejects
    the credentials.

    The hosted ``image_service.generate`` flow maps this to HTTP 503 so
    callers can distinguish "the provider rejected us" (502) from "we
    cannot reach the provider with the configured key" (503).
    """


class ImageProviderError(ImageGenError):
    """Raised when the provider call fails for a non-credential reason.

    Covers rate limiting (``reason="rate_limit"`` with
    ``retry_after_s`` in ``context`` when supplied), transient 5xx
    (``reason="transient"``), unknown model
    (``reason="model_not_found"``), request timeouts
    (``reason="timeout"``), and unsupported option pairs that the
    capability matrix rejects (``reason="unsupported_option"`` with the
    offending ``(model, size)`` or ``(model, quality)`` in ``context``).

    The ``reason`` key in ``context`` is the discriminator callers
    branch on; the message is the human-readable variant.
    """


class ContentRejectedError(ImageGenError):
    """Raised when content is refused at any of the three safety layers.

    Three call sites populate this:

    * **Categorical hard-line filter** (:mod:`persona.imagegen.safety`):
      pre-dispatch, before any backend call. ``context["reason"] =
      "hard_line_categorical"`` and ``context["category"]`` carries the
      catalogue label (``"c1"`` … ``"c6"`` per ``research.md`` §5.2).
      The triggering prompt is **never** persisted — only its sha256
      hash via ``context["prompt_sha256"]``.
    * **Provider input moderation**: the provider rejected the prompt
      before generating. ``context["reason"] = "provider_moderation"``
      and ``context["stage"] = "input"``.
    * **Provider output moderation**: the provider generated bytes but
      flagged them (e.g. fal.ai ``has_nsfw_concepts[i] = true`` per
      D-15-X-flagged-image-policy). ``context["reason"] =
      "provider_moderation"`` or ``"provider_post_gen_moderation"`` and
      ``context["stage"] = "output"``.

    The ``generate_image`` tool factory translates this into a
    ``ToolResult(is_error=True, content="content_rejected_...")`` so
    the model handles the refusal gracefully; the route layer maps it
    to HTTP 422.
    """
