"""The :class:`ImageBackend` Protocol — Spec 02 mirror for image generation.

One Protocol; every image-generation backend (OpenAI ``gpt-image-1.x``,
Flux 1.1 [pro] via fal.ai, future providers) implements it. Callers depend
on this Protocol — not on any provider SDK or transport.

Mirrors :class:`persona.backends.protocol.ChatBackend` per the Spec 15
decisions gate paragraph #1 ("Mirror Spec 02 verbatim — ``ImageBackend``
is ``ChatBackend``'s shape twin"). The :meth:`edit` method is reserved
per D-15-X-edit-protocol-reservation: declared with a Protocol-default
``NotImplementedError`` body so v1 concrete backends do NOT override and
a v1.x image-editing backend slots in without redesign.

References:
    docs/specs/phase2/spec_15/decisions.md gate paragraph #1 +
    D-15-X-edit-protocol-reservation.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from persona.imagegen.result import GeneratedImage, GenerationResult, ImageGenOptions

__all__ = ["ImageBackend"]


@runtime_checkable
class ImageBackend(Protocol):
    """Async image-generation backend — the only surface the service layer talks to.

    Implementations are constructed from an
    :class:`persona.imagegen.config.ImageBackendConfig` and expose one
    primary operation (:meth:`generate`) plus a reserved-not-implemented
    extension hook (:meth:`edit`).

    Construction-time failures (missing API key, unknown model when
    detectable cheaply) raise :class:`persona.imagegen.errors.ImageGenUnavailableError`
    immediately — never wait until first call. This matches the
    Spec 02 D-02-* construction-time-fail-fast precedent.
    """

    @property
    def provider_name(self) -> str:
        """Identifier of the configured provider (``"openai"``, ``"fal"``).

        Lowercase, ASCII. Stable across releases. Used for logging,
        observability, and the ``provider`` field of
        :class:`persona.imagegen.result.GenerationResult`.
        """

    @property
    def model_name(self) -> str:
        """Model identifier as the provider knows it.

        Echoed back in :attr:`persona.imagegen.result.GenerationResult.model`.
        Backends do not normalise — what the caller configured is what
        the response reports.
        """

    async def generate(
        self,
        prompt: str,
        *,
        options: ImageGenOptions | None = None,
    ) -> GenerationResult:
        """Single-shot image generation. Returns when the provider is done.

        The backend never writes bytes to disk — it returns the raw
        decoded bytes in :attr:`persona.imagegen.result.GeneratedImage.image_bytes`.
        The hosted service layer (spec 15 T15) persists the bytes to the
        per-persona workspace and rewrites the result with
        ``workspace_path`` populated and ``image_bytes`` zeroed.

        Args:
            prompt: The text description of the image. ``visual_style``
                merging happens upstream (spec 15 T11 ``_merge.py``)
                BEFORE this call — backends see the merged prompt.
            options: Neutral generation knobs. ``None`` means use the
                default :class:`persona.imagegen.result.ImageGenOptions`.

        Returns:
            :class:`persona.imagegen.result.GenerationResult` with one or
            more :class:`persona.imagegen.result.GeneratedImage` instances,
            the provider identifier, the model identifier, and the
            client-measured ``latency_ms``.

        Raises:
            ImageGenUnavailableError: missing or rejected credentials.
            ImageProviderError: rate limit, transient 5xx, unknown model,
                request timeout, or unsupported ``(model, size)`` /
                ``(model, quality)`` pair (``reason`` in ``context``
                discriminates).
            ContentRejectedError: provider input or output moderation
                refused the prompt or flagged the generated bytes
                (``reason`` and ``stage`` in ``context`` discriminate).
        """

    async def edit(
        self,
        input_image: GeneratedImage,
        instructions: str,
        *,
        options: ImageGenOptions | None = None,
    ) -> GenerationResult:
        """Edit an existing image with text instructions — RESERVED for v1.x.

        Per D-15-X-edit-protocol-reservation, the Protocol declares this
        signature so a v1.x image-editing backend slots in without
        redesign. v1 concrete backends do NOT override; calling
        :meth:`edit` on any v1 backend raises :class:`NotImplementedError`
        via this Protocol default.

        Args:
            input_image: The image to edit. Carries either ``image_bytes``
                (in-memory from a prior :meth:`generate` call) or
                ``workspace_path`` (loaded from disk by the service layer).
            instructions: Free-form text describing the edit.
            options: Neutral generation knobs (see :meth:`generate`).

        Returns:
            :class:`persona.imagegen.result.GenerationResult` with the
            edited image(s).

        Raises:
            NotImplementedError: always, in v1. v1.x backends override
                this default with a concrete implementation.
        """
        raise NotImplementedError("edit not supported in v1")
