"""The ``generate_image`` first-class tool factory (Spec 15 T12).

Composes a single :class:`AsyncTool` that wraps any
:class:`persona.imagegen.protocol.ImageBackend` with the four structural
defences locked by Spec 15 Phase 4 decisions:

1. **Hard-line categorical filter** (:mod:`persona.imagegen.safety`) —
   pre-dispatch, BEFORE any provider call. Trigger emits a content-
   hash-only :class:`ToolAuditEvent` (the triggering prompt itself is
   NEVER persisted; only ``hashlib.sha256(prompt)`` via
   :func:`persona.imagegen.safety.hash_prompt_for_audit`).
2. **Visual-style merge** (:mod:`persona.imagegen._merge`) — additive
   suffix-conditioning of the persona's ``identity.visual_style`` per
   D-15-4; user-specified-style heuristics yield identity so user
   wins.
3. **Neutral options validation** — :class:`ImageGenOptions` Pydantic
   model enforces the D-15-3 ``count <= 4`` cap and the closed size /
   quality preset surface; invalid kwargs from the model surface as a
   structured ``ToolResult(is_error=True)`` (mirrors the
   ``@tool``-decorator argument-validation envelope at D-03-5).
4. **Backend dispatch with adapter-level error funnel** — provider SDK
   exceptions surface as :class:`ContentRejectedError` (moderation, at
   either input or output stage) or :class:`ImageGenError`-family
   (auth / rate-limit / timeout / unsupported_option / transient).
   Both branches emit a structured :class:`ToolAuditEvent` with the
   appropriate outcome string and return a
   :class:`ToolResult(is_error=True, ...)`.

The four outcome strings landed in
:attr:`persona.tools.audit.ToolAuditEvent.metadata` are:

* ``"ok"`` — generation succeeded; image bytes are populated on the
  :class:`GenerationResult` (workspace persistence is the service
  layer's job per T15).
* ``"content_rejected_hard_line"`` — the categorical filter tripped;
  the provider was NEVER called.
* ``"content_rejected_provider"`` — the provider rejected the prompt
  (input stage) or the generated bytes (output stage); the audit
  carries ``stage`` so the operator can disambiguate.
* ``"error"`` — every other failure mode (rate limit, timeout,
  unsupported option, transient 5xx, malformed response, invalid
  options). The audit carries ``reason`` (the
  :class:`ImageGenError` subclass name) and ``provider`` /
  ``model`` for triage.

D-15-X-audit-event-extension verifies the existing
:attr:`ToolAuditEvent.metadata` ``dict[str, str]`` shape carries the
four outcome strings cleanly without a typed-Literal extension.

**Two-audit-emission discipline.** This factory emits the
persona-layer :class:`ToolAuditEvent` ("what did this persona do?"). The
API-layer ``audit_service.record`` ("what hit this endpoint?") is the
T16 route's separate emission — both deliberate, same shape as Spec 13
uploads.

References:
    docs/specs/phase2/spec_15/decisions.md gate paragraph #2 +
    D-15-4 + D-15-X-hard-line-filter + D-15-X-audit-event-extension;
    docs/specs/phase2/spec_15/tasks.md §T12;
    docs/specs/phase2/spec_15/research.md §5 + §8.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import TYPE_CHECKING

from persona.imagegen._merge import merge_visual_style
from persona.imagegen.errors import (
    ContentRejectedError,
    ImageGenError,
)
from persona.imagegen.result import ImageGenOptions
from persona.imagegen.safety import (
    hash_prompt_for_audit,
    is_hard_line_violation,
)
from persona.logging import get_logger
from persona.schema.tools import ToolResult
from persona.tools.audit import ToolAuditEvent
from persona.tools.protocol import AsyncTool, tool

if TYPE_CHECKING:
    from persona.imagegen.protocol import ImageBackend
    from persona.tools.audit import ToolAuditLogger

__all__ = ["make_generate_image_tool"]


_LOG = get_logger("imagegen.tool")


# Default factory description fed to the model. Kept terse — the model's
# system prompt is the right place for additional usage guidance; the
# persona's ``visual_style`` is merged in BEFORE the backend call so the
# model does not need to be told to invoke a style explicitly.
_DEFAULT_DESCRIPTION = (
    "Generate an image from a text description. Returns a generated image "
    "stored in the persona's workspace. Use for illustrations, diagrams, "
    "and visual aids that complement the conversation. The persona's "
    "visual style (if configured) is applied automatically."
)


def make_generate_image_tool(
    *,
    backend: ImageBackend,
    audit_logger: ToolAuditLogger | None = None,
    persona_id: str | None = None,
    persona_visual_style: str | None = None,
    description: str = _DEFAULT_DESCRIPTION,
) -> AsyncTool:
    """Build the ``generate_image`` :class:`AsyncTool`.

    Composes hard-line categorical filter, visual-style merge, options
    validation, backend dispatch, and audit emission into one tool the
    Toolbox can register. The model supplies only ``prompt`` / ``size``
    / ``count`` / ``quality`` — every other parameter (visual style,
    persona id, audit sink) is bound at factory time.

    Args:
        backend: The :class:`persona.imagegen.protocol.ImageBackend`
            implementation to dispatch to (OpenAI gpt-image-1 via
            :class:`persona.imagegen.openai_image.OpenAIImageBackend`,
            Flux 1.1 [pro] via
            :class:`persona.imagegen.fal_image.FalImageBackend`, or any
            future provider). Composition root selects per
            :func:`persona.imagegen.load_image_backend`.
        audit_logger: Optional :class:`ToolAuditLogger`. When provided,
            every dispatched call emits exactly one
            :class:`ToolAuditEvent` with ``action="execute"`` — even for
            the hard-line-rejected path (audit fires BEFORE the
            provider is consulted; the audit trail is the forensic
            record of what was *attempted*).
        persona_id: Persona identifier for audit records. ``None`` for
            CLI development; audit lines then route to
            ``_cli.tools.jsonl``.
        persona_visual_style: The persona's
            :attr:`persona.schema.persona.PersonaIdentity.visual_style`
            (T10) which is merged into the prompt at dispatch time per
            D-15-4. ``None`` / empty / whitespace-only yields the
            identity branch in :func:`merge_visual_style` (no merge).
        description: Tool description fed to the model. The default
            covers the spec §5 wording; override to surface persona-
            specific guidance.

    Returns:
        An :class:`AsyncTool` named ``generate_image``. The persona's
        ``tools`` allow-list (Spec 03 D-03-7) gates whether a given
        persona can dispatch ``generate_image`` at all — the same way
        ``code_execution`` / ``file_write`` / MCP tools are gated.

    Notes:
        The returned tool follows the @tool / Toolbox contract unchanged:
        argument-validation errors and body-raised exceptions are
        converted to ``ToolResult(is_error=True, ...)`` by the ``@tool``
        decorator (D-03-5).
        :class:`persona.imagegen.errors.ImageGenError` subclasses (the
        domain-exception family) are caught here at the body and
        surfaced as structured failure results so the model can
        recover (e.g. provider rate limit → model explains "try again
        shortly"; content rejection → model offers an alternative).

        The backend NEVER touches disk inside this tool — the
        :class:`GenerationResult` carries raw bytes in
        :attr:`persona.imagegen.result.GeneratedImage.image_bytes`. The
        API service layer (Spec 15 T15) persists those bytes to the
        per-persona workspace and rewrites ``workspace_path`` on the
        outbound response. This factory's :class:`ToolResult` content
        is a short human-readable summary (image dimensions + count +
        media type); the structured ``data`` field carries the per-
        image metadata the service / model use downstream.
    """

    @tool(name="generate_image", description=description)
    async def generate_image(
        prompt: str,
        size: str = "1024x1024",
        count: int = 1,
        quality: str = "standard",
    ) -> ToolResult:
        # 1. Hard-line categorical filter — runs BEFORE the backend call.
        # On trigger: emit a content-hash-only audit (NEVER the prompt
        # itself) and return a structured failure ToolResult.
        triggered, category = is_hard_line_violation(prompt)
        if triggered:
            prompt_sha256 = hash_prompt_for_audit(prompt)
            _emit_hard_line_audit(
                audit_logger=audit_logger,
                persona_id=persona_id,
                provider=backend.provider_name,
                model=backend.model_name,
                category=category,
                prompt_sha256=prompt_sha256,
            )
            _LOG.warning(
                "generate_image hard-line trigger; provider not called",
                persona_id=persona_id or "<unknown>",
                category=category or "",
                prompt_sha256=prompt_sha256,
            )
            return ToolResult(
                tool_name="generate_image",
                content="content_rejected_hard_line",
                is_error=True,
                metadata={
                    "outcome": "content_rejected_hard_line",
                    "category": category or "",
                    "prompt_sha256": prompt_sha256,
                },
            )

        # 2. Merge visual_style — identity branch when style is None /
        #    empty / whitespace-only OR the user prompt already
        #    specifies a style (user wins per D-15-4).
        merged_prompt = merge_visual_style(prompt, persona_visual_style)

        # 3. Validate ImageGenOptions — closes the closed-preset surface
        #    + the D-15-3 count<=2 cap. Bad values from the model land as
        #    structured failure (the @tool decorator's validation
        #    envelope already covers schema-level errors; this catches
        #    e.g. unknown ``size`` strings that pass the str type check
        #    but fail the Literal validation).
        try:
            options = ImageGenOptions(
                size=size,  # type: ignore[arg-type]
                count=count,
                quality=quality,  # type: ignore[arg-type]
            )
        except Exception as exc:  # noqa: BLE001 — ValidationError + value coercion + Literal misses
            _emit_options_error_audit(
                audit_logger=audit_logger,
                persona_id=persona_id,
                provider=backend.provider_name,
                model=backend.model_name,
                detail=str(exc),
            )
            return ToolResult(
                tool_name="generate_image",
                content=f"invalid_options: {exc}",
                is_error=True,
                metadata={
                    "outcome": "error",
                    "reason": "invalid_options",
                    "provider": backend.provider_name,
                    "model": backend.model_name,
                },
            )

        # 4. Backend dispatch — adapter-level error funnel surfaces SDK
        #    exceptions as ContentRejectedError (moderation) or
        #    ImageGenError-family (auth / rate / transient / etc.).
        try:
            result = await backend.generate(merged_prompt, options=options)
        except ContentRejectedError as exc:
            stage = exc.context.get("stage", "")
            reason = exc.context.get("reason", "provider_moderation")
            _emit_provider_rejection_audit(
                audit_logger=audit_logger,
                persona_id=persona_id,
                provider=backend.provider_name,
                model=backend.model_name,
                stage=stage,
                reason=reason,
            )
            _LOG.info(
                "generate_image provider rejection",
                persona_id=persona_id or "<unknown>",
                provider=backend.provider_name,
                stage=stage,
                reason=reason,
            )
            return ToolResult(
                tool_name="generate_image",
                content=f"content_rejected_provider: {exc}",
                is_error=True,
                metadata={
                    "outcome": "content_rejected_provider",
                    "stage": stage,
                    "reason": reason,
                    "provider": backend.provider_name,
                    "model": backend.model_name,
                },
            )
        except ImageGenError as exc:
            error_type = type(exc).__name__
            reason = exc.context.get("reason", error_type)
            _emit_error_audit(
                audit_logger=audit_logger,
                persona_id=persona_id,
                provider=backend.provider_name,
                model=backend.model_name,
                error_type=error_type,
                reason=reason,
            )
            _LOG.warning(
                "generate_image backend failure",
                persona_id=persona_id or "<unknown>",
                provider=backend.provider_name,
                error_type=error_type,
                reason=reason,
            )
            return ToolResult(
                tool_name="generate_image",
                content=f"{error_type}: {exc}",
                is_error=True,
                metadata={
                    "outcome": "error",
                    "reason": reason,
                    "error_type": error_type,
                    "provider": backend.provider_name,
                    "model": backend.model_name,
                },
            )

        # 5. Success — emit one audit event with outcome=ok and return a
        #    structured ToolResult. ``data`` carries per-image metadata
        #    (workspace_path is None at this layer — T15 service rewrites
        #    after disk persistence); ``content`` is a short human-
        #    readable summary the model can echo.
        image_count = len(result.images)
        _emit_success_audit(
            audit_logger=audit_logger,
            persona_id=persona_id,
            provider=result.provider,
            model=result.model,
            image_count=image_count,
            latency_ms=result.latency_ms,
            size=options.size,
        )
        media_types = sorted({img.media_type for img in result.images})
        # The first image's dimensions are representative (the provider
        # returns one consistent size per request); we surface them for
        # the model to echo without verbatim-rendering each image's
        # dimensions in ``content``.
        first = result.images[0]
        content_summary = (
            f"generated {image_count} image"
            f"{'s' if image_count != 1 else ''} "
            f"({first.width}x{first.height}, {', '.join(media_types)})"
        )
        return ToolResult(
            tool_name="generate_image",
            content=content_summary,
            is_error=False,
            metadata={
                "outcome": "ok",
                "provider": result.provider,
                "model": result.model,
                "latency_ms": f"{result.latency_ms:.1f}",
                "image_count": str(image_count),
                "size": options.size,
            },
            data={
                "provider": result.provider,
                "model": result.model,
                "latency_ms": result.latency_ms,
                "images": [
                    {
                        "workspace_path": img.workspace_path,
                        "media_type": img.media_type,
                        "width": img.width,
                        "height": img.height,
                        "revised_prompt": img.revised_prompt,
                    }
                    for img in result.images
                ],
            },
        )

    return generate_image


# ---------------------------------------------------------------------------
# Audit-event emitters.
#
# Each emitter is a thin helper around :class:`ToolAuditEvent` construction
# so the @tool body stays readable. The four outcome strings (``ok`` /
# ``content_rejected_provider`` / ``content_rejected_hard_line`` /
# ``error``) land in :attr:`ToolAuditEvent.metadata["outcome"]` cleanly
# without a struct change (D-15-X-audit-event-extension).
# ---------------------------------------------------------------------------


def _emit_hard_line_audit(
    *,
    audit_logger: ToolAuditLogger | None,
    persona_id: str | None,
    provider: str,
    model: str,
    category: str | None,
    prompt_sha256: str,
) -> None:
    """Emit one ``outcome=content_rejected_hard_line`` audit event.

    The triggering prompt is **never** persisted — only the sha256 hash
    via ``metadata["prompt_sha256"]`` (D-15-X-hard-line-filter). The
    ``resource`` field carries the same hash so an operator searching by
    hash can correlate the audit event to the trigger without revealing
    the content.
    """
    if audit_logger is None:
        return
    audit_logger.emit(
        ToolAuditEvent(
            timestamp=datetime.now(UTC),
            persona_id=persona_id,
            tool_name="generate_image",
            action="execute",
            resource=f"sha256:{prompt_sha256}",
            is_error=True,
            metadata={
                "outcome": "content_rejected_hard_line",
                "category": category or "",
                "prompt_sha256": prompt_sha256,
                "provider": provider,
                "model": model,
            },
        )
    )


def _emit_provider_rejection_audit(
    *,
    audit_logger: ToolAuditLogger | None,
    persona_id: str | None,
    provider: str,
    model: str,
    stage: str,
    reason: str,
) -> None:
    """Emit one ``outcome=content_rejected_provider`` audit event.

    Distinguished from the hard-line audit by the ``outcome`` value AND
    by carrying ``stage`` (``"input"`` / ``"output"``) so post-hoc
    analysis can separate prompt-rejection from generated-bytes-flagged
    rejections (D-15-X-flagged-image-policy).
    """
    if audit_logger is None:
        return
    audit_logger.emit(
        ToolAuditEvent(
            timestamp=datetime.now(UTC),
            persona_id=persona_id,
            tool_name="generate_image",
            action="execute",
            resource=provider,
            is_error=True,
            metadata={
                "outcome": "content_rejected_provider",
                "stage": stage,
                "reason": reason,
                "provider": provider,
                "model": model,
            },
        )
    )


def _emit_error_audit(
    *,
    audit_logger: ToolAuditLogger | None,
    persona_id: str | None,
    provider: str,
    model: str,
    error_type: str,
    reason: str,
) -> None:
    """Emit one ``outcome=error`` audit event for a backend-raised failure.

    Covers every non-moderation :class:`ImageGenError` subclass
    (:class:`ImageGenUnavailableError` for auth failures,
    :class:`ImageProviderError` for rate-limit / transient /
    unsupported_option / timeout). The ``error_type`` /  ``reason`` pair
    is the discriminator callers branch on; the API route layer maps
    these to HTTP status codes (503 for unavailable, 502 for transient).
    """
    if audit_logger is None:
        return
    audit_logger.emit(
        ToolAuditEvent(
            timestamp=datetime.now(UTC),
            persona_id=persona_id,
            tool_name="generate_image",
            action="execute",
            resource=provider,
            is_error=True,
            metadata={
                "outcome": "error",
                "error_type": error_type,
                "reason": reason,
                "provider": provider,
                "model": model,
            },
        )
    )


def _emit_options_error_audit(
    *,
    audit_logger: ToolAuditLogger | None,
    persona_id: str | None,
    provider: str,
    model: str,
    detail: str,
) -> None:
    """Emit one ``outcome=error reason=invalid_options`` audit event.

    Fires when :class:`ImageGenOptions` validation rejects the model-
    supplied ``size`` / ``count`` / ``quality``. The audit trail records
    the attempt + the validation detail so the operator can see if a
    given model is repeatedly tripping the cap.
    """
    if audit_logger is None:
        return
    audit_logger.emit(
        ToolAuditEvent(
            timestamp=datetime.now(UTC),
            persona_id=persona_id,
            tool_name="generate_image",
            action="execute",
            resource=provider,
            is_error=True,
            metadata={
                "outcome": "error",
                "reason": "invalid_options",
                "detail": detail,
                "provider": provider,
                "model": model,
            },
        )
    )


def _emit_success_audit(
    *,
    audit_logger: ToolAuditLogger | None,
    persona_id: str | None,
    provider: str,
    model: str,
    image_count: int,
    latency_ms: float,
    size: str,
) -> None:
    """Emit one ``outcome=ok`` audit event for a successful generation.

    The success audit complements the failure audits so an operator can
    answer "how many image-gen calls happened on this persona, and how
    many succeeded?" by counting ``outcome=ok`` events directly.
    """
    if audit_logger is None:
        return
    audit_logger.emit(
        ToolAuditEvent(
            timestamp=datetime.now(UTC),
            persona_id=persona_id,
            tool_name="generate_image",
            action="execute",
            resource=provider,
            is_error=False,
            metadata={
                "outcome": "ok",
                "provider": provider,
                "model": model,
                "image_count": str(image_count),
                "latency_ms": f"{latency_ms:.1f}",
                "size": size,
            },
        )
    )
